<?php 

/** 
 * Remove a bunch of stuff from the <head> section that is autogenerated by WordPress
 */
remove_action('wp_head', 'rsd_link');
remove_action('wp_head', 'wlwmanifest_link');
remove_action('wp_head', 'wp_generator');
remove_action('wp_head', 'start_post_rel_link');
remove_action('wp_head', 'index_rel_link');
remove_action('wp_head', 'adjacent_posts_rel_link');
remove_action('wp_head', 'wp_shortlink_wp_head', 10, 0);

remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
remove_action( 'wp_print_styles', 'print_emoji_styles' );

/**
 * Remove the jQuery dependency on the frontend. The admin side of the
 * site does rely on it though, so don't remove it there.
 */
function deregister_jquery() {  
    if ( !is_admin() ) {
        wp_deregister_script('jquery');
    }
}  
add_action('wp_enqueue_scripts', 'deregister_jquery'); 

/**
 * Remove the ability to embed pages/posts from 3rd party sites.
 * This does not affect embedding videos. 
 * wp-embed was introduced in v4.4 
 */
function tcp_deregister_scripts(){
    wp_deregister_script( 'wp-embed' );
}
  add_action( 'wp_footer', 'tcp_deregister_scripts' );

/**
 * Remove the generated classses in the nav menu to clean up appearence. 
 * @link http://www.wp3layouts.com/wp/remove-every-class-id-wordpress-wp_nav_menu/
 *  */ 
function remove_css_id_filter($var) {
    return is_array($var) ? array_intersect($var, array('current-menu-item')) : '';
} 
add_filter( 'page_css_class', 'remove_css_id_filter', 100, 1);
add_filter( 'nav_menu_item_id', 'remove_css_id_filter', 100, 1);
add_filter( 'nav_menu_css_class', 'remove_css_id_filter', 100, 1);